# Generated by Django 4.2.2 on 2023-08-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
