# Generated by Django 4.2.2 on 2023-08-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_rating_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='product_images/{0.name}/%Y/%m/%d/'),
        ),
    ]
